apiVersion: v2
name: docspell
description: Docspell is a Document Management System (DMS), a system that asists in organizing your piles of documents

type: application
version: 0.1.1
appVersion: "0.40.0"
