apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "docspell.labels" . | nindent 4 }}
  name: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "docspell.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: solr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "docspell.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: solr
    spec:
      containers:
        - args:
            - solr-precreate
            - docspell
          image: solr:9
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8983/solr/docspell/admin/ping
            failureThreshold: 2
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          name: docspell-solr
          resources: {}
          volumeMounts:
            - mountPath: /var/solr
              name: docspell-solr-data
      restartPolicy: Always
      volumes:
        - name: docspell-solr-data
          persistentVolumeClaim:
            claimName: docspell-solr-data