apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "docspell.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-db
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "docspell.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "docspell.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: dbname
            - name: POSTGRES_PASSWORD
              value: dbpass
            - name: POSTGRES_USER
              value: dbuser
          image: postgres:15.2
          name: postgres-db
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: docspell-postgres-data
      restartPolicy: Always
      volumes:
        - name: docspell-postgres-data
          persistentVolumeClaim:
            claimName: docspell-postgres-data