apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db
    {{- include "docspell.labels" . | nindent 4 }}
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "docspell.selectorLabels" . | nindent 6 }}
      {{- include "docspell.labels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/docspell-default: "true"
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: dbname
            - name: POSTGRES_PASSWORD
              value: dbpass
            - name: POSTGRES_USER
              value: dbuser
          image: postgres:15.2
          name: postgres-db
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: docspell-postgres-data
      restartPolicy: Always
      volumes:
        - name: docspell-postgres-data
          persistentVolumeClaim:
            claimName: docspell-postgres-data
status: {}
