apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: docspell-default
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "docspell.selectorLabels" . | nindent 14 }}
  podSelector:
    matchLabels:
      {{- include "docspell.selectorLabels" . | nindent 6 }}