apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    {{- include "docspell.labels" . | nindent 4 }}
  name: joex
spec:
  ports:
    - name: "7878"
      port: 7878
      targetPort: 7878
  selector:
    {{- include "docspell.labels" . | nindent 4 }}
status:
  loadBalancer: {}
