apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: restserver
  name: restserver
spec:
  ports:
    - name: "7880"
      port: 7880
      targetPort: 7880
  selector:
    io.kompose.service: restserver
status:
  loadBalancer: {}
