apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "docspell.labels" . | nindent 4 }}
  name: restserver
spec:
  ports:
    - name: "7880"
      port: 7880
      targetPort: 7880
  selector:
    {{- include "docspell.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: restserver
