apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: solr
  name: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: solr
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/docspell-default: "true"
        io.kompose.service: solr
    spec:
      containers:
        - args:
            - solr-precreate
            - docspell
          image: solr:9
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8983/solr/docspell/admin/ping
            failureThreshold: 2
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          name: docspell-solr
          resources: {}
          volumeMounts:
            - mountPath: /var/solr
              name: docspell-solr-data
      restartPolicy: Always
      volumes:
        - name: docspell-solr-data
          persistentVolumeClaim:
            claimName: docspell-solr-data
status: {}
